import { Language } from '../types/cv';

export const translations: Record<Language, Record<string, string>> = {
  en: {
    summary: 'Professional Summary',
    experiences: 'Experience',
    education: 'Education',
    skills: 'Skills',
    projects: 'Projects',
    certifications: 'Certifications',
    languages: 'Languages',
    achievements: 'Achievements',
    volunteers: 'Volunteer Experience',
    publications: 'Publications',
    references: 'References',
    present: 'Present',
  },
  tr: {
    summary: 'Özet',
    experiences: 'Deneyim',
    education: 'Eğitim',
    skills: 'Yetenekler',
    projects: 'Projeler',
    certifications: 'Sertifikalar',
    languages: 'Diller',
    achievements: 'Başarılar',
    volunteers: 'Gönüllü Çalışmalar',
    publications: 'Yayınlar',
    references: 'Referanslar',
    present: 'Devam Ediyor',
  },
  fr: {
    summary: 'Profil Professionnel',
    experiences: 'Expérience',
    education: 'Formation',
    skills: 'Compétences',
    projects: 'Projets',
    certifications: 'Certifications',
    languages: 'Langues',
    achievements: 'Réalisations',
    volunteers: 'Bénévolat',
    publications: 'Publications',
    references: 'Références',
    present: 'Présent',
  },
  de: {
    summary: 'Zusammenfassung',
    experiences: 'Berufserfahrung',
    education: 'Bildung',
    skills: 'Fähigkeiten',
    projects: 'Projekte',
    certifications: 'Zertifizierungen',
    languages: 'Sprachen',
    achievements: 'Erfolge',
    volunteers: 'Ehrenamt',
    publications: 'Publikationen',
    references: 'Referenzen',
    present: 'Heute',
  },
  es: {
    summary: 'Resumen Profesional',
    experiences: 'Experiencia',
    education: 'Educación',
    skills: 'Habilidades',
    projects: 'Proyectos',
    certifications: 'Certificaciones',
    languages: 'Idiomas',
    achievements: 'Logros',
    volunteers: 'Voluntariado',
    publications: 'Publicaciones',
    references: 'Referencias',
    present: 'Actual',
  },
};

export const getTranslation = (lang: Language, key: string): string => {
  return translations[lang]?.[key] || translations['en'][key] || key;
};
